---
platform: linux

image_resource: 
  type: docker-image
  source: 
    repository: microsoft/aspnetcore-build
    tag: "latest"

inputs: 
  - name: git-repo
  - name: resource-version

outputs:
  - name: artifact

run:
  path: git-repo/ci/scripts/build.sh
