resources:
  - name: git-repo
    type: git
    source: 
      uri: {{git-repo}}
      branch: {{git-repo-branch}} 

  - name: gh-release
    type: github-release
    source:
      repository: {{git-repo-name}}
      user: {{git-user}}
      access_token: {{git-access-token}}

  - name: version
    type: semver
    source:
      driver: git
      uri: git@github.com:cerdmann/category-service.git
      branch: master
      file: version
      private_key: {{git-ssh-key}}
      git_user: {{git-user-email}} 

  - name: deploy-dev
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-dev-space}}

  - name: deploy-stage
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-stage-space}}

  - name: deploy-prod
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-prod-space}}

jobs:
  - name: build
    serial_groups: [version]
    plan: 
      - get: git-repo
        trigger: true
      - get: version
        params: {bump: minor}
      - task: build
        file: git-repo/ci/tasks/build.yml
      - put: gh-release 
        params:
          name: ./artifact/release_name.txt
          tag: ./artifact/release_tag.txt
          body: ./artifact/release_notes.md
          commitish: ./artifact/release_commitish.txt
          globs:
          - ./artifact/category-service.*.tar.gz

  - name: deploy-dev
    plan:
      - aggregate:
        - get: git-repo
          trigger: true
          passed: [build]
      - put: deploy-dev
        params:
          manifest: git-repo/manifest.yml
          current_app_name: category-service
          path: artifact

  - name: deploy-stage
    plan:
      - aggregate:
        - get: git-repo
          passed: [deploy-dev]
      - put: deploy-stage
        params:
          manifest: git-repo/manifest.yml
          current_app_name: category-service
          path: artifact

  - name: deploy-prod
    plan:
      - aggregate:
        - get: git-repo
          passed: [deploy-stage]
      - put: deploy-prod
        params:
          manifest: git-repo/manifest.yml
          current_app_name: category-service
          path: artifact
